### ISSUE TITLE
`MufluxReco.py` broken for MC data

### ISSUE THREAD

**Issue by olantwin** [ShipSoft/FairShip#139] opened 2018-09-14 13:10 UTC
As of #127 MC data can not be reconstructed without the `--realPR` flag:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/o/olantwin/SHiP_Software/FairShip/macro/MufluxReco.py", line 366, in <module>
    SHiP.reconstruct()
  File "/afs/cern.ch/user/o/olantwin/SHiP_Software/FairShip/python/MufluxDigiReco.py", line 136, in reconstruct
    ntracks = self.findTracks()
  File "/afs/cern.ch/user/o/olantwin/SHiP_Software/FairShip/python/MufluxDigiReco.py", line 1456, in findTracks
    (n_tracks, n_recognized, n_clones, n_ghosts, n_others) = self.target_metrics(track_hits)
  File "/afs/cern.ch/user/o/olantwin/SHiP_Software/FairShip/python/MufluxDigiReco.py", line 720, in target_metrics
    atrack_y_tagger = atrack['y_tagger']
KeyError: 'y_tagger'
```

@hushchyn-mikhail : Could you please have a look at this? I suspect some checks need to be introduced, or some fallback behaviour for the case where `y_tagger` does not exist.

If `--realPR` is set, the reconstruction finished successfully.

**Comment by olantwin** [comment] 2018-09-25 15:01
@hushchyn-mikhail The issue I mentioned in the meeting.

**Comment by ThomasRuf** [comment] 2018-09-26 05:58
The problem is that this script uses the geometry defined by the geofile. When we moved to use the new magnetic field interface, sometime in spring (?), this is not anymore possible. The geometry has to be built from scratch.  

SHiP = MufluxDigiReco.MufluxDigiReco(outFile,fgeo)
self.sGeo = fgeo.FAIRGeom <-  this does not work anymore

**Comment by ThomasRuf** [comment] 2018-09-26 06:06
I see another problem with MufluxDigiReco. When I look at the simulated TDC values, I find entries above 2000ns. With a drift velocity of ShipGeo.MufluxSpectrometer.v_drift = 1./(72*u.ns/u.mm), and a drift radius of ShipGeo.MufluxSpectrometer.InnerTubeDiameter/2. = 1.815cm, the maximum drift time is 1306.8ns, 30% of the entries are above this value!

**Comment by ThomasRuf** [comment] 2018-09-26 06:19
apparently, a t0 is being added for each event, up to 1microsecond, which we don't have in real data. After correcting for this, the TDC distribution looks ok.

**Comment by olantwin** [comment] 2018-09-26 08:09
> The problem is that this script uses the geometry defined by the geofile. When we moved to use the new magnetic field interface, sometime in spring (?), this is not anymore possible. The geometry has to be built from scratch.
> 
> SHiP = MufluxDigiReco.MufluxDigiReco(outFile,fgeo)
> self.sGeo = fgeo.FAIRGeom <- this does not work anymore

I agree that this is a problem, but this does not explain the crash. So there's at least another issue somewhere.

**Comment by ThomasRuf** [comment] 2018-09-27 08:15
should I repair it or is anybody else copying the recipe from ShipReco?

**Comment by olantwin** [comment] 2018-09-27 09:33
Is there a way we can avoid duplicating the code in several places?

Maybe we can have a single python module that sets up the geometry that other code can import?

Then we also only have to remember to update these things once and don't need to keep many scripts in sync.

**Comment by ThomasRuf** [comment] 2018-09-27 09:49
Setting up the geometry takes only 2 lines of code: 
run = ROOT.FairRunSim()
modules = charmDet_conf.configure(run,ShipGeo)

the parameters (ShipGeo) to be used depends on the use case, simulation, reconstruction, real data, ...

for simulation and reconstruction of real data, one has to take the parameters from the config file:
from ShipGeoConfig import ConfigRegistry
ShipGeo = ConfigRegistry.loadpy("$FAIRSHIP/geometry/charm-geometry_config.py")

for reconstruction of simulated data, we take the parameters from the geofile, to be insync:

fgeo = ROOT.TFile.Open(geoFile)
from ShipGeoConfig import ConfigRegistry
from rootpyPickler import Unpickler
upkl    = Unpickler(fgeo)
ShipGeo = upkl.load('ShipGeo')

not sure it is worse to put this in an external script.

**Comment by olantwin** [comment] 2018-09-27 09:52
You're right, this would not really be simplified.

**Comment by ThomasRuf** [comment] 2018-09-27 10:15
I started to fix MufluxReco. Problem now with MufluxDigiReco, this was never used with real data, I think, always for simulation. Digitizing and reconstructing are not really separated. Will take some time to clean it up.

**Comment by ThomasRuf** [comment] 2021-02-23 08:13
all fixed in branch muflux. See procedures in charmdet/runSimulation.py and charmdet/runReconstruction.py

**Closed by ThomasRuf** 2021-02-23 08:13 UTC
