### ISSUE TITLE
eventdisplay

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/FairShip#368] opened 2020-11-17 14:00 UTC
Problem so far only appears on SLC7, Ubuntu 20.04 OK. 
when starting eventdisplay the following error pops up:
class DrawVetoDigi(ROOT.FairTask):
   KeyError: 'fStreamProcessing'

wasn't able to figure out what is so special about fStreamProcessing variable in FairTask.h. Removing this variable and all its occurrences moves the problem to KeyError: 'fLogger', so I guess the original problem is something else.

**Comment by ThomasRuf** [comment] 2020-11-18 08:08
Short update. Error can be reproduced without eventdisplay. When defining a python class inheriting from any class known to ROOT:

 import ROOT
class MyClass(ROOT.ShipHit):
 " My Class"

--> 
  File "<stdin>", line 1, in <module>
KeyError: 'fDetectorID'

it always complains about the last protected data member. Adding another variable:
  protected:
    Float_t fdigi;   ///< digitized detector hit
    Int_t   fDetectorID;     ///< Detector unique identifier
    Int_t stupidRoot;

will move the error to stupidRoot variable.

**Comment by olantwin** [comment] 2020-11-18 09:25
This is very strange. I suggest we report this to the ROOT team, as it seems like it is some side-effect of the new PyROOT backend...

**Comment by ThomasRuf** [comment] 2020-11-18 09:31
yes, but remember that in order to bypass the TPythia8 problem, for which we got no help from the ROOT team, we modified by hand core/metacling/src/TCling.cxx . I am currently building a version with raw ROOT, and checking if the error is still there. Then, we can send a bug report.

**Comment by ThomasRuf** [comment] 2020-11-18 13:16
OK, tested it with plain ROOT tag v6-22-02, 17 August 2020. Same error on SLC7. What is the best way to contact the ROOT team? My report about TPythia8 was never answered.

**Comment by ThomasRuf** [comment] 2020-11-18 13:24
One more info. For SLC7, we need to make our own toolchain. On Ubuntu 20.04, I was using gcc 9.3.0-17. The latest which is available from https://github.com/alisw/gcc-toolchain is  v7.3.0-alice2 . Could this cause the difference between SLC7 and Ubuntu?

**Comment by olantwin** [comment] 2020-11-18 19:55
> One more info. For SLC7, we need to make our own toolchain. On Ubuntu 20.04, I was using gcc 9.3.0-17. The latest which is available from https://github.com/alisw/gcc-toolchain is v7.3.0-alice2 . Could this cause the difference between SLC7 and Ubuntu?

Can you create an issue in shipdist for this? 7.3 is pretty old, we should try to update to at least 8 or something like that.

I don't think it should make much of a difference, if the code compiles without issue, but the fewer versions of GCC we need to test with/support, the better, as compiler changes seem to be one of the biggest issues when building all of shipdist, and usually require a lot of changes.

**Comment by olantwin** [comment] 2020-11-18 19:57
> OK, tested it with plain ROOT tag v6-22-02, 17 August 2020. Same error on SLC7. What is the best way to contact the ROOT team? My report about TPythia8 was never answered.

If you create an issue, I'll contact the lead PyRoot developer and discuss with him what could be causing it. The ROOT developers are usually also pretty responsive on mattermost and the forums, but I think usually they ask that one creates a ticket first.

I believe the ROOT team now migrated to using github as well, so creating an issue here: https://github.com/root-project/root/issues might be better than Jira.

**Comment by ThomasRuf** [comment] 2020-11-22 13:06
with lot of difficulties I eventually succeeded to open an issue:
https://github.com/root-project/root/issues/6856

**Comment by olantwin** [comment] 2020-11-24 09:04
Apparently this is an instance of [ROOT-11025](https://sft.its.cern.ch/jira/browse/ROOT-11025), which is fixed in 6.22/04.

Due to a regression in 6.22/04, we should probably wait for 6.22/06.

**Comment by olantwin** [comment] 2023-03-20 15:41
Closing for now as we are using ROOT 6.26 now. We can reopen, if this issue reappears.

**Closed by olantwin** 2023-03-20 15:41 UTC
