### ISSUE TITLE
Numpy arrays can not be pickled by rootpyPickler since move to python3

### ISSUE THREAD

**Issue by MassiFL** [ShipSoft/FairShip#446] opened 2023-10-19 08:42 UTC
Test:
In geometry/geometry_config.py, add:

``` python
import numpy as numpy
irange = numpy.arange(0,9,1)
c.itest = 1.0 + 3.141596 * irange # c is from "ConfigRegistry.register_config("basic") as c"
for i in range(0,len(c.itest)): print(c.itest[i])    # just to make sure it was defined
```

Result, it crashes:

```
OBJ: FairParRootFile    ./ship.params.conical.MuonBack-TGeant4_D.root    : 0 at: 0x5567d8978e30
Root file I/O ./ship.params.conical.MuonBack-TGeant4_D.root is open
detector I/Os:  FairGenericParIo
Traceback (most recent call last):
  File "/home/eric/ShipSoft-5july2023/FairShip/macro/run_simScript.py", line 574, in <module>
    saveBasicParameters.execute("%s/geofile_full.%s.root" % (options.outputDir, tag),ship_geo)
  File "/home/eric/ShipSoft-5july2023/sw/ubuntu2204_x86-64/FairShip/master-local1/python/saveBasicParameters.py", line 44, in execute
    pkl.dump(o,name)    
  File "/home/eric/ShipSoft-5july2023/sw/ubuntu2204_x86-64/FairShip/master-local1/python/rootpyPickler.py", line 172, in dump
    super(Pickler, self).dump(obj)
  File "/home/eric/ShipSoft-5july2023/sw/ubuntu2204_x86-64/FairShip/master-local1/python/rootpyPickler.py", line 104, in write
    return self.__s.write(_protect(s).decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 347: invalid continuation byte
```

It used to work...

**Comment by olantwin** [comment] 2023-10-19 08:49
When did this work?

At first glance this seems to be an encoding issue in the pickler. This might have worked in python2, but since the code in question hasn't been touched in a while, I would be surprised if it ever worked in python3.

Should generally be fixable, but might be worth thinking about moving away from the copy-pasted rootpyPickler to a more standard serialisation format (with code we don't have to maintain ourselves).

**Comment by antonioiuliano2** [comment] 2023-10-19 09:32
This after I added the lines you mentioned at the end of geometry/geometry_config.py and did the rebuild.
--- a/geometry/geometry_config.py
+++ b/geometry/geometry_config.py
@@ -911,3 +911,8 @@ with ConfigRegistry.register_config("basic") as c:
     c.UpstreamTagger.X_Strip64 = 1.534 * u.cm
     c.UpstreamTagger.Y_Strip64 = 111 * u.cm
     c.UpstreamTagger.Z_Position = c.tauMudet.zMudetC + (c.tauMudet.Ztot)/2 + 12.0*u.cm
+
+    import numpy as numpy
+    irange = numpy.arange(0,9,1)
+    c.itest = 1.0 + 3.141596 * irange # c is from "ConfigRegistry.register_config("basic") as c"
+    for i in range(0,len(c.itest)): print(c.itest[i]) 

I am using the CVMFS build, May22, for ubuntu20.

**Comment by antonioiuliano2** [comment] 2023-10-19 09:43
Never mind, I saw that the error happens at the end of run_simScript, when trying to write the parameter file.

**Comment by antonioiuliano2** [comment] 2023-10-19 10:00
It seems that already in the past there was work in FairShip to make pickle work with Python3:

https://github.com/rootpy/rootpy/issues/808

> Thanks for reporting this!
> 
> > It used to work...
> 
> When did this work?
> 
> At first glance this seems to be an encoding issue in the pickler. This might have worked in python2, but since the code in question hasn't been touched in a while, I would be surprised if it ever worked in python3.
> 
> Should generally be fixable, but might be worth thinking about moving away from the copy-pasted rootpyPickler to a more standard serialisation format (with code we don't have to maintain ourselves).

**Comment by MassiFL** [comment] 2023-10-19 10:13
> Thanks for reporting this!
> 
> > It used to work...
> 
> When did this work?
> 
> At first glance this seems to be an encoding issue in the pickler. This might have worked in python2, but since the code in question hasn't been touched in a while, I would be surprised if it ever worked in python3.
> 
> Should generally be fixable, but might be worth thinking about moving away from the copy-pasted rootpyPickler to a more standard serialisation format (with code we don't have to maintain ourselves).

Yes, was python2 (2020 fairship version)

**Comment by olantwin** [comment] 2023-10-19 10:22
Maybe this phase between P and TDR might be a good time to re-evaluate how we store this information in the root files? Pickling was never intended for this kind of use (as discussed in the issue Antonio referenced).

The pickler is essentially unmaintainable (and rootpy is unmaintained since a few years ago), so while we could probably fix this particular bug, I'd be keen to move away from it in the short to medium term.

As a workaround, can you use a list or python (not numpy) array?

**Comment by olantwin** [comment] 2023-10-19 10:24
Once the geometry_config.py is evaluated, it should essentially be a nested dict of constants. For this, storage as a json/toml/yaml or similar file would make sense, which can be read into python or C++ objects again very easily.

**Comment by MassiFL** [comment] 2023-10-19 10:27
> Maybe this phase between P and TDR might be a good time to re-evaluate how we store this information in the root files? Pickling was never intended for this kind of use (as discussed in the issue Antonio referenced).
> 
> The pickler is essentially unmaintainable (and rootpy is unmaintained since a few years ago), so while we could probably fix this particular bug, I'd be keen to move away from it in the short to medium term.
> 
> As a workaround, can you use a list or python (not numpy) array?

Of course, no problem to use a workaround. I am already in business. Pas de souci. 
(it's just, you know, ... python lists do not facilitate arithmetics)

**Comment by ThomasRuf** [comment] 2023-10-19 12:29
Regarding: 'utf-8' codec can't decode byte 0xf0 in position 347: invalid continuation byte
Can it be that you changed your editor, or editor setting regarding end of line, carriage return? Or you made a copy and paste from another source?

**Comment by olantwin** [comment] 2023-10-19 12:45
As far as I understand this is a problem with the encoding of the dumped object, not an editor issue (which could result in an incorrectly encoded .py file).

**Comment by ThomasRuf** [comment] 2023-10-19 13:14
Can reproduce the issue:
from rootpyPickler import Pickler
sGeo = {}
import numpy as numpy
irange = numpy.arange(0,9,1)
sGeo['itest'] = 1.0 + 3.141596 * irange
fp = ROOT.TFile.Open('test.root','recreate')
pkl = Pickler(fp)
pkl.dump(sGeo,'sGeo')

...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 269: invalid continuation byte

rootPyPickler was not made to make arbitrary objects persistent. Was made to store python dictionaries in a root file together with ROOT objects. Your itest is an object of <class 'numpy.ndarray'>.  If it worked in the past, it was just pure luck.

**Comment by olantwin** [comment] 2023-10-21 09:10
As rootpyPickler was not designed for arbitrary objects, I would close this issue.

If we move to a different solution for storing the geometry config, we can think about supporting numpy arrays during the design phase.

If you come up with a fix, I'm happy to merge it, but I personally would focus on moving beyond the pickler.

**Closed by olantwin** 2023-10-21 09:10 UTC

**Comment by ThomasRuf** [comment] 2023-10-22 12:06
This should work: 
...
tmp =  1.0 + 3.141596 * irange
sGeo['itest'] = list(tmp)
...
