### ISSUE TITLE
Cannot activate transparency in Event Display

### ISSUE THREAD

**Issue by antonioiuliano2** [ShipSoft/FairShip#380] opened 2021-01-14 10:42 UTC
Dear all,

I have found another issue in the Event Display GUI. I tried to make volume transparent with the button at **SHiP actions/switch transparent mode on/off**, however instead I got the following error:

Traceback (most recent call last):
  File "/home/utente/SHIPBUILD/sw/ubuntu1604_x86-64/FairShip/master-1/macro/evd_transparentMode.py", line 4, in <module>
    if SHiPDisplay.TransparentMode == 0 : SHiPDisplay.transparentMode()
AttributeError: 'FairTask' object has no attribute 'TransparentMode'

This happens to both FairShip and sndsw displays. I am investigating the origin.

Best regards,
Antonio

**Comment by olantwin** [comment] 2021-01-14 10:45
Does adjusting the case of `TransparentMode` to `transparentMode` fix it?

**Comment by antonioiuliano2** [comment] 2021-01-14 10:55
No, TransparentMode is the name of the attibute, transparentMode is the name of the function. 
However, I am discovering some details.

If I type manually in the terminal:

`SHiPDisplay.transparentMode('on')`

it works, and it also has the attribute TransparentMode. 
However, if I do just as in evd_transparentMode 

```
lsOfGlobals = ROOT.gROOT.GetListOfGlobals()
SHiPDisplay = lsOfGlobals.FindObject('SHiP Displayer')
```
SHiPDisplay becomes from a cppyy_internal.Dispatcher2 a FairTask instance (the primitive class of EventLoop). Here, it loses the additional attribute and method call.

**Comment by olantwin** [comment] 2021-01-14 10:59
Ah, I see. The cast seems to be a problem.

Seems the type of pointers to abstract base classes is handled differently now with the new (py)ROOT version,.

**Comment by antonioiuliano2** [comment] 2021-01-14 11:12
So, if I understand correctly Python's "duck typing" for classes:

evd_transparentMode.py asks SHiPDisplay to "quack" (TransparentMode). since pyROOT stores (or retrieves) it uncorrectly from the Globals List, it crashes. Instead, the instance stored internally from eventDisplay.py has the required attribute and "quacks" correctly.

**Comment by olantwin** [comment] 2021-01-14 11:20
Well, I think more useful for the understanding here is the C++ side, considering the type of the pointers, and the type of the object pointed to. The way this is translated to python seems to have changed in PyROOT.

**Comment by ThomasRuf** [comment] 2021-01-22 12:40
Is there a solution to this issue? Is there any other way to access the global object SHiPDisplay?
ls = ROOT.gROOT.GetListOfGlobals()
ls.FindObject('SHiP Displayer') --> <cppyy.gbl.FairTask object at 0xf056490> 
SHiPDisplay  -->  <cppyy.gbl.__cppyy_internal.Dispatcher4 object at 0xf056490>

it seems via ROOT, one gets only the mother class, not the methods of the daughter class, also the pointer is the same. It seems some casting is missing. Does this exist in python?

**Comment by olantwin** [comment] 2021-01-22 12:51
From the pointer we get, we could try to create a new object of the same class, which should then have the correct methods and attributes.

Maybe better though would be to make the SHiPDisplay object global in the first place, so that we can access it everywhere (or make it a singleton)?

**Comment by ThomasRuf** [comment] 2021-01-22 12:54
OK, found a solution. Doesn't look very elegant, but works. Create a file sndsw/macro/eveGlobal.py with content, SHiPDisplay = 0. Update the variable in eventDisplay:
SHiPDisplay = EventLoop()
import eveGlobal
eveGlobal.SHiPDisplay = SHiPDisplay

than, in the other module, instead of using ROOT do
  import eveGlobal
  SHiPDisplay  = eveGlobal.SHiPDisplay

**Comment by ThomasRuf** [comment] 2021-01-22 12:54
open for any other solution requiring less code.

**Comment by olantwin** [comment] 2021-01-22 13:02
Maybe there is an easier way to retrieve it by looking at the currently existing python objects (using pythons __blabla__ objects)?

Alternatively, we could maybe pass SHiPDisplay to the function as an argument (or maybe even better: make it a method of SHiPDisplay)

**Comment by ThomasRuf** [comment] 2021-01-22 13:07
it has to work together with;
 b.SetCommand('TPython::ExecScript("'+os.environ['FAIRSHIP']+'/macro/evd_addParticleFollower.py")')

as I said, any suggestion requiring less code than the solution above is welcome. Of course, there could be also solutions requiring to rewrite the whole setup.

**Comment by olantwin** [comment] 2021-01-22 14:25
That of course complicates life immensely...

**Comment by olantwin** [comment] 2021-02-02 15:31
This issue apparently arises because python-C++ cross-inheritance has been completely reimplemented. 

I'll try to write a short reproducer, but it seems the PyROOT team would consider this a regression that should be fixed.

**Comment by olantwin** [comment] 2021-02-02 16:03
Which version did this originally work with?
With the old pyROOT it also does not seem to work, so it must be some other change in earlier ROOT versions.

**Comment by ThomasRuf** [comment] 2021-02-02 16:20
I guess, it worked for:
 tag: "v6-14-00-ship"
    source: https://github.com/ShipSoft/root

**Comment by olantwin** [comment] 2021-02-02 16:21
Apparently this was the code that allowed it to work in the past: https://github.com/root-project/root/blob/master/bindings/pyroot_legacy/src/RootWrapper.cxx#L945

Anyway, the workaround we now found is not too bad, and maybe a better way to do things than using `GetListOfGlobals` in the first place.
Maybe we can consider re-using the `global_variables.py` module instead of creating a second module that is only used as a workaround.

@ThomasRuf , I think you can close this issue.

**Comment by wlav** [comment] 2021-02-15 21:43
@ThomasRuf: hope I find you well!

The presence of `Dispatcher` classes indicates to me that an instance is first created of a Python cross-derived type, then that instance is send to C++ land and retrieved back into Python from C++ land.

It's a bit subtle to find the original Python instance back after round-tripping through C++ (Python knows about C++, but C++ does not know about Python), but with cppyy 1.9.3 (just released) this should now work as expected.

**Comment by ThomasRuf** [comment] 2021-02-17 06:53
I will try this new version as soon as possible. Thanks a lot, Thomas

**Comment by fairlyons** [comment] 2024-09-06 11:19
Transparent mode button in event display seems to be working now.

**Closed by fairlyons** 2024-09-06 11:19 UTC
Labels: Event Display
